# Training-specific configuration for SelectiveMagnoViT
# This extends base_config.yml with specific settings for training experiments

experiment:
  name: "selective_magno_vit_training"
  version: "v1.0"
  seed: 42
  description: "Standard training configuration for SelectiveMagnoViT"

# Data paths - override these based on your setup
data:
  raw_root: "/path/to/raw_imagenette"
  preprocessed_root: "/path/to/preprocessed"
  magno_dir: "${data.preprocessed_root}/magno_images"
  lines_dir: "${data.preprocessed_root}/line_drawings"
  color_dir: "${data.preprocessed_root}/color_images"

# Model architecture
model:
  patch_percentage: 0.4  # Select 40% of patches
  img_size: 64
  patch_size: 4
  num_classes: 10
  vit_model_name: "vit_tiny_patch16_224.augreg_in21k"
  pretrained: true

  # Patch selector parameters
  selector:
    threshold: 0.3
    gaussian_std: 0.25

# Training hyperparameters
training:
  epochs: 100
  batch_size: 32
  learning_rate: 1.0e-4
  weight_decay: 0.01
  patience: 20
  num_workers: 4

  # Optimizer settings
  optimizer: "adamw"
  scheduler: "cosine"
  warmup_epochs: 5

  # Data augmentation
  augmentation:
    random_crop_scale: [0.8, 1.0]
    random_horizontal_flip: true
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.1
      hue: 0.0

# Preprocessing settings
preprocessing:
  line_drawing_style: "opensketch_style"
  magno_size: 64
  color_size: 256

# Output directories
output:
  checkpoint_dir: "checkpoints"
  results_dir: "results"
  logs_dir: "logs"
  tensorboard_dir: "logs/tensorboard"

# Logging
logging:
  level: "INFO"
  log_every_n_steps: 50
  save_epoch_freq: 5
  log_model_info: true

# Evaluation
evaluation:
  compute_confusion_matrix: true
  save_predictions: false
  visualize_patches: true
  num_visualization_samples: 10
